services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./app/static/audio:/app/app/static/audio
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    command: python app.py